CREATE TABLE tutor (
	id_tutor  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome varchar(100),
	endereco varchar(150),
	telefone varchar(15),
	email varchar(100)
)  

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Adao', 'Rua Guerra Mundial - 190' , 18 19478595, brasilguerra@gmail.com);

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Beatriz', 'Avenida da Liberdade - 250', 19 98765432, 'beatrizliberdade@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Carlos', 'Rua das Flores - 75', 21 12345678, 'carlos.flores@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Daniela', 'Praça Central - 300', 18 23456789, 'daniela.central@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Eduardo', 'Estrada do Sol - 150', 22 34567890, 'eduardo.solar@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Fernanda', 'Rua dos Limoeiros - 90', 19 45678901, 'fernanda.limoeiros@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Gabriel', 'Beco da Esperança - 20', 21 56789012, 'gabriel.esperanca@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Helena', 'Avenida do Parque - 400', 22 67890123, 'helena.parque@gmail.com');

INSERT INTO tutor
	(nome, endereco, telefone, email)
VALUES 
	('Igor', 'Rua das Acácias - 30', 19 78901234, 'igor.acacias@gmail.com');

INSERT INTO tutor
	(nome, enderco, telefone, email)
VALUES 
	('Juliana', 'Praça das Águas - 85', 21 89012345, 'juliana.aguas@gmail.com');


CREATE TABLE paciente (
	id_paciente  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100), 
	especie VARCHAR(50), 
	raca  VARCHAR(50),
	idade  INT,
	peso numeric(15,2),
	id_tutor integer,
	FOREIGN KEY (id_tutor) REFERENCES tutor(id_tutor)
)

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Thor', 'cachorro', 'pit bull', 3, 20)
	
INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Luna', 'cachorro', 'labrador', 2, 25);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Milo', 'cachorro', 'bulldog', 4, 15);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Bella', 'cachorro', 'golden retriever', 5, 30);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Nina', 'gato', 'persa', 3, 4);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Leo', 'cachorro', 'pastor alemão', 6, 40);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Zara', 'gato', 'siamês', 2, 3);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Rocky', 'cachorro', 'boxer', 1, 22);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Chloe', 'gato', 'angorá', 4, 5);

INSERT INTO paciente 
	(nome, especie, raca, idade, peso)
VALUES 
	('Max', 'cachorro', 'beagle', 3, 10);


CREATE TABLE veterinario (
	id_veterinario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100),
	especie VARCHAR(50),
	raca VARCHAR(50),
	idade INT,
	peso numeric(15,2)
)

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Thor', 'cachorro', 'pit bull', 3, 20);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Luna', 'cachorro', 'labrador', 2, 25);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Milo', 'cachorro', 'bulldog', 4, 15);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Bella', 'cachorro', 'golden retriever', 5, 30);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Nina', 'gato', 'persa', 3, 4);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Leo', 'cachorro', 'pastor alemão', 6, 40);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Zara', 'gato', 'siamês', 2, 3);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Rocky', 'cachorro', 'boxer', 1, 22);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Chloe', 'gato', 'angorá', 4, 5);

INSERT INTO veterinario 
	(nome, especie, raca, idade, peso)
VALUES 
	('Max', 'cachorro', 'beagle', 3, 10);


CREATE TABLE agendamento (
	id_agendamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	data_hora timestamp,
	motivo varchar(50),
	id_paciente integer,
	FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente),
	id_veterinario integer,
	FOREIGN KEY (id_veterinario) REFERENCES veterinario(id_veterinario)
)

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-02 09:00:00', 'Vacinação');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-03 11:30:00', 'Exame de Sangue');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-04 16:00:00', 'Consulta de Rotina');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-05 10:00:00', 'Avaliação Comportamental');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-06 13:00:00', 'Consulta de Dermatologia');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-07 15:30:00', 'Cirurgia');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-08 12:15:00', 'Consulta de Nutrição');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-09 17:45:00', 'Tratamento Dental');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-10 08:30:00', 'Consulta de Emergência');

INSERT INTO agendamento 
	(data_hora, motivo)
VALUES 
	('2024-10-11 14:00:00', 'Consulta de Seguimento');


CREATE TABLE medicamento (
	id_medicamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100),
	descricao varchar(50),
	preco (DECIMAL(10,2))
)

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Dipirona', 'Analgésico e antitérmico', 15.50);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Amoxicilina', 'Antibiótico', 25.00);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Ranitidina', 'Antiacídico', 12.75);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Ciprofloxacino', 'Antibiótico', 30.00);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Prednisona', 'Anti-inflamatório', 28.20);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Vetmedin', 'Cardiotônico', 40.00);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Bravecto', 'Antiparasitário', 50.00);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Cerenia', 'Antiemético', 35.00);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('Clavulin', 'Antibiótico', 32.50);

INSERT INTO medicamento 
	(nome, descricao, preco)
VALUES 
	('NexGard', 'Antiparasitário', 45.00);


CREATE TABLE receita (
	id_receita integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	data_emissao date,
	id_agendamento integer,
	FOREIGN KEY (id_agendamento) REFERENCES agendamento(id_agendamento)
)

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-01');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-02');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-03');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-04');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-05');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-06');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-07');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-08');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-09');

INSERT INTO receita 
	(data_emissao)
VALUES 
	('2024-09-10');

CREATE TABLE itens_receita (
    id_item_receita INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INTEGER NOT NULL,
    dosagem VARCHAR(50) NOT NULL,
    id_receita INTEGER NOT NULL,
    id_medicamento INTEGER NOT NULL,
    CONSTRAINT id_medicamento FOREIGN KEY (id_medicamento) REFERENCES medicamento (id_medicamento),
    CONSTRAINT id_receita FOREIGN KEY (id_receita) REFERENCES receita (id_receita)
);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(2, '500mg', 1, 1);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(1, '250mg', 1, 2);

INSERT INTO itens_receita 
(	quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(3, '10ml', 2, 3);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(5, '5mg', 2, 4);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(1, '15mg', 3, 5);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(4, '100mg', 3, 6);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(2, '1ml', 4, 7);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(6, '200mg', 4, 8);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(3, '50mg', 5, 9);

INSERT INTO itens_receita 
	(quantidade, dosagem, id_receita, id_medicamento)
VALUES 
	(1, '10mg', 5, 10);
